@extends('frontend.layouts.dashboard')

@section('contentHeader')

@stop

@section('content')
    <div class="signin-wrap">
        <div class="signin-background"></div>
        <div class="ss-container signin">
            <div class="signin__new">
                <p>
                    Welcome to GlobalParcelForward.com
                </p>
                <p>
                    Shoppers around the world use our service to forward parcels globally. We are the only parcel
                    forwarding company that has the resources, expertise, customer dedication and global experience to
                    make shopping and shipping from the UK fast, dependable, reliable and affordable.
                </p>
                <div class="register">
                    <h3 class="register__title">Not a member?</h3>
                    <p class="register__desc">Register for free and start shipping today!</p>
                    <a class="button button--small button--white" href="{!! url()->route('registration.plan') !!}">Register</a>
                </div>
            </div>
            <div class="signin__already">
                <div class="already">
                    <h3 class="already__title">Login </h3>
                    <p class="already__desc">
                        By Signing in you are confirming that you have read and agreed to our <a
                                href="{!! url('terms-trade') !!}">Terms of Trade. </a>
                    </p>
                    <p class="already__desc error" id="login_message_box" style="display: none;">
                    </p>
                    @if(session()->has('message') && session()->has('class'))
                        @if(session('class')=='danger')
                            <p class="already__desc error">{!! session('message') !!}</p>
                        @elseif(session('class')=='success')
                            <p class="already__desc success">{!! session('message') !!}</p>
                        @endif
                    @endif
                    <form id="login_form" class="already__form">
                        {!!Form::text('email', old('email'), ['class'=>'form-control','placeholder'=>'Email Address'])!!}
                        {!!Form::password('password', ['class'=>'form-control','placeholder'=>'Password'])!!}
                        <a href="{!! url()->route('password.request') !!}">
                            Forgot your password?
                        </a>
                        <button type="submit" class="button button--small button--accent">Signin</button>
                    </form>
                    <div class="authen" style="display: none;" id="authy_form">
                        <p class="authen__desc">
                            Please enter authentication code generated by your app, to complete
                            sign in, and using this site
                        </p>
                        <div class="authen__code code">
                            <div class="code__title">
                                <span>Authentication Code</span>
                                <a href="javascript" data-tooltip="I am tooltip text.">What is this ?</a>
                            </div>
                            <form id="authy_code_form">
                                <div class="code__input">
                                    <input type="hidden" name="user_id">
                                    <input data-id="0" type="number" maxlength="1" name="auth_code[0]"/>
                                    <input data-id="1" type="number" maxlength="1" name="auth_code[1]"/>
                                    <input data-id="2" type="number" maxlength="1" name="auth_code[2]"/>
                                    <input data-id="3" type="number" maxlength="1" name="auth_code[3]"/>
                                    <input data-id="4" type="number" maxlength="1" name="auth_code[4]"/>
                                    <input data-id="5" type="number" maxlength="1" name="auth_code[5]"/>
                                    <div class="code__btn">
                                        <button class="button button--accent" type="submit">
                                            <i class="fas fa-angle-right fa-3x"></i>
                                        </button>
                                        <button class="button button--text" type="reset">Reset</button>
                                    </div>
                                </div>
                                <p class="form__error error" style="display: none;"></p>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
  @include('frontend.popups.verify_successful')
@stop

@section('contentFooter')
    <script>
        $(document).ready(function () {
            login_form.init();
        });
        @if(isset($popup) && $popup)
          $("#verified_successful").modal("show");
        @endif
    </script>
@stop
